# Global properties go here
spring:
   datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
mvc:
   max-size-trace-payload: 50000
jms:
   listener-concurrency: 1-5
   agreement-queue: sandbox.agreement      
---
# Dev properties go here
spring:
   profiles: dev
   datasource:
      username: sa
      password:
   jpa:
      hibernate:
         ddl-auto: validate
---
# UAT properties go here
spring:
   profiles: uat
   datasource:
      username: sa
      password:
         