# Global properties go here
spring:
   datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
jms:
   listener-concurrency: 1-5      
---
# Dev properties go here
spring:
   profiles: dev
   datasource:
      username: sa
      password:
---
# UAT properties go here
spring:
   profiles: uat
   datasource:
      username: sa
      password:
         